server.port=8082
# Nom de l'application
spring.application.name=webapp

# Configuration PostgreSQL (Connexion simplifiée grâce au mode 'trust')
spring.datasource.url=jdbc:postgresql://localhost:5432/db_chercheurs
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Pour que Hibernate crée les tables automatiquement
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#Configuration upload
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB